version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-jessie-node-browsers-legacy
      - image: postgres:latest
        environment:
          - POSTGRES_USER=postgres

    working_directory: ~/repo
    steps:
      - checkout
      # Install PostgreSQL client toolsで足りないディレクトリを追加
      - run: sudo mkdir -p /usr/share/man/man1
      - run: sudo mkdir -p /usr/share/man/man7

      - run:
          name: Install PostgreSQL client tools
          command: |
            sudo apt-get -y update && sudo apt-get install -y postgresql-client
      - run:
          name: Install and enable pdo_pgsql php extension
          command: |
            sudo apt-get update && sudo apt-get install libpq-dev
            sudo docker-php-ext-install pdo_pgsql && docker-php-ext-enable pdo_pgsql
      - run:
          name: Populate .env
          command: cp .env.testing .env
      - run:
          name: Update composer
          command: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run:
          name: Install php dependencies
          command: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run:
          name: Prep the database and user, install extensions etc.
          command: |
            sudo -u root psql -h 127.0.0.1 -U postgres -c "create database homestead"
            sudo -u root psql -h 127.0.0.1 -U postgres -c "create user homestead password 'secret'"
            sudo -u root psql -h 127.0.0.1 -U postgres -c "grant all on database homestead to homestead"
            sudo -u root psql -h 127.0.0.1 -U postgres homestead -c "create extension citext"
      - run:
          name: Populate .env
          command: php artisan key:generate
      - run:
          name: Run database migrations
          command: php artisan migrate --force
          background: true
      - run:
         name: Start Chrome Driver
         command: ./vendor/laravel/dusk/bin/chromedriver-linux
         background: true
      - run:
         name: Run Laravel Server
         command: php artisan serve
         background: true
      - run:
         name: Run Seeder
         command: php artisan db:seed
      - run:
         name: Run Laravel Dusk Tests
         command: php artisan dusk